engines:
  duplication:
    enabled: true
    config:
      languages:
      - rust

  fixme:
    enabled: true

  markdownlint:
    enabled: true

  shellcheck:
    enabled: true

ratings:
  paths:
    - "**.rs"
    - "**.sh"
    - "**.md"
