language: rust

os:
  - linux

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - libgtk-3-dev

env:
  - GTK=latest
  - GTK=3.4

script:
  - ./build.sh

matrix:
  allow_failures:
    - rust: nightly
    - env: GTK=latest
