language: rust

os:
  - linux

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - libgtk-3-dev

env:
  - GTK=3.18

before_script:
  - cargo install clippy

script:
  - ./build.sh
  - cargo clippy --verbose -- -D warnings

matrix:
  allow_failures:
    - rust: nightly
