language: rust

cache: cargo

os:
  - linux

rust:
  - stable
  - beta
  - nightly

before_script:
  - ./clippy.sh install

script:
  - ./clippy.sh test

#matrix:
  #allow_failures:
    #- rust: nightly
