language: rust

os:
  - linux

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - libgtk-3-dev

env:
  - GTK=3.18

before_script:
  - ./clippy.sh install

script:
  - ./build.sh
  - ./clippy.sh test

#matrix:
  #allow_failures:
    #- rust: nightly
