[package]
name = "feroxide-gui"
<<<<<<< HEAD
version = "1.0.0"
=======
version = "0.0.2"
>>>>>>> 714ddde (Convert to Piston library)
authors = ["feroxide"]

description = "A basic chemistry simulator (GUI)"
documentation = "https://github.com/feroxide/feroxide-gui"
homepage = "https://feroxide.github.io/feroxide/"
repository = "https://github.com/feroxide/feroxide-gui"

readme = "README.md"

keywords = ["chemistry", "simulator", "mit"]
categories = ["gui", "science"]

license-file = "LICENSE"


[dependencies]
# feroxide = "1.3.0"
piston_window = "0.70.0"
image = "0.15.0"
vecmath = "0.3.0"

[dependencies.feroxide]
version = "1.3.1"
features = [ "no_utf" ]
